### ISSUE TITLE
0.5.1 for Scala 2.10.4

### ISSUE THREAD

**Issue by eparejatobes** [ohnosequences/nice-sbt-settings#26]
Is this published? I couldn't resolve it.

**Comment by laughedelic** [comment]
Ahm, I didn't get what you mean.. It's a plugin, so it exists only for scala-2.10. Show me the error message, please.

**Comment by eparejatobes** [comment]
It's not resolved. But it's about the template in era7bio/scala, the resolver for the plugin is wrong (it won't affect you because most likely you have it locally anyway)

**Comment by laughedelic** [comment]
Should be solved by https://github.com/era7bio/scala.g8/commit/6a0410d99426e8f21f7665150c41b50ac31ba4d5
