### ISSUE TITLE
releasing 0.6.0 ?

### ISSUE THREAD

**Issue by eparejatobes** [ohnosequences/nice-sbt-settings#29]
@laughedelic I'd like to have this soon, at least a `RC1`. What is the current state?

**Comment by laughedelic** [comment]
yep, I'll do it

**Comment by laughedelic** [comment]
I'll close #30 and #31 and release 0.6.0 next week. There is much to refactor, but probably not now..

**Comment by laughedelic** [comment]
Finally done: [`v0.6.0`](https://github.com/ohnosequences/nice-sbt-settings/releases/tag/v0.6.0). #30 and #31 will go to the next release.

**Comment by eparejatobes** [comment]
OK. #31 is not so important now. What's #30 about?

**Comment by laughedelic** [comment]
It's about changing version to the release one, then back to snapshot for tests, then again to release.

**Comment by laughedelic** [comment]
or moving tests step before release notes check...

**Comment by eparejatobes** [comment]
better have tests run before the release notes thing

**Comment by laughedelic** [comment]
ok :+1:
