### ISSUE TITLE
0.7.0-M1?

### ISSUE THREAD

**Issue by eparejatobes** [ohnosequences/nice-sbt-settings#42]
@laughedelic what do you want to have before a milestone release?

**Comment by laughedelic** [comment]
nothing, we're using 0.7.0-SNAPSHOT everywhere for quite a long time. I can just release 0.7.0 as is. All the other thing will go to the next release.

**Comment by eparejatobes** [comment]
fine :+1:

**Comment by laughedelic** [comment]
Done: [v0.7.0](https://github.com/ohnosequences/nice-sbt-settings/releases/tag/v0.7.0)
