### ISSUE TITLE
git error when publishing API docs

### ISSUE THREAD

**Issue by eparejatobes** [ohnosequences/nice-sbt-settings#55]
In a release process

```
Do you want to generate and publish API docs to gh-pages? (y/n) y
[warn] error: Unknown subcommand: get-url (from [git remote])
```

**Comment by eparejatobes** [comment]
with 0.8.0-RC2

**Comment by laughedelic** [comment]
Which version of git do you have?

**Comment by eparejatobes** [comment]
`2.5.5`

**Comment by laughedelic** [comment]
OK, so are you going to upgrade git or you want some workaround here for when this subcommand is not available?

**Comment by eparejatobes** [comment]
2.7 was released in **2016**, not 2015. I will build git from source then, no problem.
